apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: docker.io/library/spring-cloud-config-server:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 9296
          env:
            - name: eureka.service-url.default
              valueFrom:
                configMapKeyRef:
                  name: config-server
                  key: eureka.service-url.default
            - name: eureka.host-name
              valueFrom:
                configMapKeyRef:
                  name: config-server
                  key: eureka.host-name
