apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  labels:
    name: config-server-service
    app: my-stays
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    name: config-server-pod
    app: my-stays