server:
  servlet:
    context-path: /config-server
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IBS-Skillset/configuration
  application:
    name: config-server