server:
  port: 9296
  servlet:
    context-path: /config-server
management:
  endpoints:
    web:
      exposure:
        include: '*'
health:
  config:
    enabled: false

spring:
  application:
    name: config-server
  cloud:
    bootstrap:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/IBS-Skillset/Config
          clone-on-start: true
eureka:
  instance:
    hostname:  config-server
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${HOST_REGISTRY:localhost}:8761/eureka/


