server:
  port: 9296
  servlet:
    context-path: /config-server
management:
  endpoints:
    web:
      exposure:
        include: '*'
health:
  config:
    enabled: false

spring:
  application:
    name: config-server
  cloud:
    kubernetes:
      config:
        enabled: true
        name: ${spring.application.name}