---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: beta-app
  labels:
    app: config-server
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server-api
          image: 306472407007.dkr.ecr.ap-south-1.amazonaws.com/ibs-skillset-happystays/config-server:a4c840f
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9296
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: HOST_REGISTRY
              value: service-registry
